#!/bin/bash

LIB="libft"
LIB_CPY="../libft_cpy"
LIB_NEW="../libft"

cp -r $LIB $LIB_CPY
rm -rf $LIB
rm -rf $LIB_NEW
mv $LIB_CPY $LIB_NEW

if [ -d "$HEADER_DIR" ]; then
	cp $LIB/libft.h $HEADER_DIR/
fi
